project: default
destinationServer: https://kubernetes.default.svc
applications: {}
#  kube-prometheus-stack:
#    namespace: monitoring
#    source:
#      chart: kube-prometheus-stack
#      repoURL: https://prometheus-community.github.io/helm-charts
#      targetRevision: 13.4.1
#      helm:
#        releaseName: monitoring
#        values: |
#          grafana:
#            enabled: false
#    ignoreDifferences:
#    - group: apiextensions.k8s.io
#      kind: CustomResourceDefinition
#      name: 
#      jsonPointers:
#      - /preserveUnknownFields