{{- $dot := . }} 
{{- range $key, $value := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ $dot.Release.Namespace }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $value.namespace }}
  project: default
  source:
{{- toYaml $value.source | nindent 4 }}
  syncPolicy:
{{- with $value.syncPolicy.automated }}
    automated:
    {{- toYaml . | nindent 6 }}
  {{- end }}
    syncOptions:
      - CreateNamespace=true
  {{- with $value.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
