apiVersion: v2
name: collection-baseline
version: 1.0.0
dependencies:
  - name: project-contour
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: cert-manager
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: monitoring
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: reloader
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: forecastle
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: konfigurator
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0