apiVersion: v2
name: collection-baseline
version: 1.0.0
dependencies:
  - name: project-contour
    repository: https://nolte.github.io/argo-charts/
    version: 1.1.0
  - name: cert-manager
    repository: https://nolte.github.io/argo-charts/
    version: 1.1.0
  - name: monitoring
    repository: https://nolte.github.io/argo-charts/
    version: 1.1.0

    