apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/app-of-app
    repoURL: https://github.com/nolte/argo-bootstrap.git
    targetRevision: HEAD
    helm:
      values: |
        applications:
          # https://bitnami.com/stack/contour/helm
          contour:
            namespace: projectcontour
            source:
              chart: contour
              repoURL: https://charts.bitnami.com/bitnami
              targetRevision: 4.1.0
              helm:
                values: | 
                  envoy:
                    service:
                      type: NodePort
                  contour:
                    manageCRDs: false
          # https://artifacthub.io/packages/helm/jetstack/cert-manager    
          cert-manager:
            namespace: cert-manager
            source:
              chart: cert-manager
              repoURL: https://charts.jetstack.io
              targetRevision: v1.1.0

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
