apiVersion: v2
name: collection-devops
version: 1.0.0
dependencies:
  - name: minio
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: argo-workflow
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: argocd-image-updater
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: argo-cd
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: vault-operator
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: harbor
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0
  - name: keycloak
    repository: https://nolte.github.io/argo-charts/
    version: 1.6.0