apiVersion: v2
name: collection-devops
version: 1.0.0
dependencies:
  - name: minio
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.1
  - name: argo-workflow
    repository: https://nolte.github.io/argo-charts/
    version: 1.3.0
  - name: argocd-image-updater
    repository: https://nolte.github.io/argo-charts/
    version: 1.2.1
  - name: argo-cd
    repository: https://nolte.github.io/argo-charts/
    version: 1.3.0

    